import { createInitialTowerCatalog } from '../../data/gameConfig';

export const createPlayerState = () => ({
  x: 0,
  y: 0,
  vx: 0,
  vy: 0,
  speed: 180,
  radius: 12,
  hp: 100,
  maxHp: 100,
  lastShoot: 0,
  shootCd: 0.5,
  damage: 8,
  range: 200,
});

export const createRuntimeState = () => ({
  player: createPlayerState(),
  camera: { x: 0, y: 0 },
  keys: { w: false, a: false, s: false, d: false },
  joystick: { active: false, startX: 0, startY: 0, currentX: 0, currentY: 0, dirX: 0, dirY: 0 },
  pointer: { x: 0, y: 0, active: false },
  dragPlacement: { active: false, kind: 'tower', entityId: null, towerId: null, pointerX: 0, pointerY: 0, worldX: 0, worldY: 0, canPlace: false, invalidReason: null },
  buildBarRect: null,
  debugPanelRect: null,
  enemies: [],
  towers: [],
  projectiles: [],
  drops: [],
  particles: [],
  impactWaves: [],
  hazards: [],
  floatingTexts: [],
  nextTowerUid: 1,
  nextEnemyUid: 1,
  lastTime: 0,
  gameTime: 0,
  money: 20,
  towerCatalog: createInitialTowerCatalog(),
  wave: { number: 1, queue: [], spawnInterval: 0.9, spawnTimer: 0, boss: null, bossSpawned: false, awaitingReward: false, pendingRewardBossUid: null },
  difficultyMultiplier: 1,
  isMobile: false,
  mode: 'normal',
  debugOptions: { infiniteMoney: false, infiniteHealth: false },
});
