import {originalFrameData} from '../characters/originalFrameData.js';
import {originalLayerData} from '../characters/originalLayerData.js';
const uiIds=["arrowDown", "arrowLeft", "arrowRight", "arrowUp", "blueprint", "button-blue", "button-coral", "button-honey", "button-sage", "card", "check", "close", "divider", "gem", "heart", "keycap", "leafLogo", "panel", "reward-accent", "root-shadow-ground", "root-shadow", "shattered", "title-end", "title-start", "upgradeBlueprint", "warning", "wave", "supplement/boss", "supplement/clock", "supplement/muted", "supplement/pause", "supplement/phase", "supplement/sound", "world/hp-frame"];
export const uiSourcePaths=Object.freeze([...new Set([...uiIds.map(id=>'art/original/v1/'+id+'.png'),'art/original/v1/characters/basic/neutral-repaired.png','art/original/v1/characters/burst/neutral-composite.png',...Object.values(originalLayerData).map(d=>d.icon),...Object.values(originalFrameData).map(d=>(d.frames.neutral??d.frames['neutral-right']).src)])]);
const pending=new Map(),listeners=new Set(),failures=new Map();
export const getUiSourceFailures=()=>[...failures.values()];
export const subscribeUiSourceFailures=callback=>{listeners.add(callback);return()=>listeners.delete(callback)};
export function reportUiSourceFailure(url,reason='PNG decode/image load failed'){if(failures.has(url))return;failures.set(url,{url,reason});for(const listener of listeners)listener(getUiSourceFailures())}
export function ensureUiSource(url){if(!pending.has(url)){const image=new Image();image.src=url;pending.set(url,image.decode().then(()=>image).catch(error=>{reportUiSourceFailure(url,String(error?.message??error));return null}))}return pending.get(url)}
export async function loadUiSourceAssets({baseUrl='',signal,onError}={}){if(signal?.aborted)return{status:'aborted',images:[],errors:[],sourcePaths:uiSourcePaths};const unsubscribe=subscribeUiSourceFailures(errors=>onError?.(errors));signal?.addEventListener('abort',unsubscribe,{once:true});const prefix=baseUrl?baseUrl.replace(/\/$/,'')+'/':'/';const images=await Promise.all(uiSourcePaths.map(path=>ensureUiSource(prefix+path)));const errors=getUiSourceFailures();return{status:errors.length?'failed':'ready',images,errors,sourcePaths:uiSourcePaths}}
