"""Art-only r02 integration. Reads approved r01 contracts; writes only this revision."""
from pathlib import Path
import json, hashlib, re

ROOT=Path('D:/WebProjects/GeoGuard')
BASE=ROOT/'docs/art-direction/sticker-bible-2026-10-01/production-art-2026-10-02'
OUT=Path(__file__).resolve().parent
if (OUT/'packet.json').exists(): raise SystemExit('Sealed revision; do not rewrite.')
def read(path): return json.loads(path.read_text(encoding='utf-8'))
def write(name,obj): (OUT/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()
fpath=BASE/'friendly/submissions/r03/production-split.json'
epath=BASE/'enemies/submissions/r02/production-split.json'
bpath=BASE/'bosses-mechanics/submissions/r03/production-split.json'
friendly,enemies,bosses=map(read,[fpath,epath,bpath])
old=read(BASE/'effects-ui/submissions/r01/boss-source-map.json')
catalog=read(BASE/'effects-ui/submissions/r01/runtime-catalog.json')
source_index={a['ability']:a for a in old['abilities']}

cells={}
def cell(key,file,title,pivot,lifecycle,layer):
    cells[key]={'board':key.split('/')[0],'cell':key.split('/')[1],'file':file,'title':title,'pivot':pivot,'lifecycle':lifecycle,'layer':layer,'reviewStatus':'submitted_not_accepted','artForm':'design reference only; not exported sprite'}
for i,(id,kind) in enumerate([('PLAYER','basic'),('BASIC','basic'),('CANNON','cannon'),('SNIPER','sniper'),('RAPID','basic'),('MORTAR','cannon'),('FROST','basic'),('RAIL','sniper'),('BURST','basic'),('SENTINEL','basic')],1):
    cell(f'B01/P{i:02d}','b01-friendly-projectiles.png',id+' / '+kind,'P=center; M=flash rear; local +X',{'projectile':'actual spawn to hit/life end, velocity/radius/code owned','flash':'proposed successful shot event; no existing dedicated emitter event','stop':'source lifetime; flash cosmetic'},'L3 projectile / L4 flash')
state_titles=['SHIELD','SLOW','FROZEN','JAM','ARMOR','PHASE','BURROW','HIT FLASH','OPEN','ENRAGED','SHADOW','LEVEL','GROUND','HP','PHASE INTRO','LINKS']
state_rules=[
 'shield>0; ratio=shield/maxShield; stop when empty', 'actual slowRatio/slowTimer eligibility',
 'tower.frozenTimer>0; ends on timer expiry', 'actual jamAura range/getTowerFireRateFactor; proposed cosmetic overlay, no hazard',
 'actual armoredTimer>0, ends on expiry', 'actual enemy.phased alpha state; no new PHASE child',
 'burrowed ground mark; actual emerge event soil effect ends cosmetically', 'actual hitFlash mask timer; cannot replace anatomy',
 'actual damageTakenMultiplier>1 whole-body indication; not belly weak point', 'actual partnerFallen, never a fourth phase',
 'fixed projection root R; follows owner world position; local root never drifts', 'code.level0..3 => Lv1..4; 1..4 external dots, no new organs',
 'low-contrast world grid/decal; no collision', 'actual hp/maxHp; independent owner health',
 'phaseIntroTimer; decorative ring reuse for proposed heal aura/fuse cue uses actual eligibility, not damage',
 'actual windup/lockedTarget/sacrificeTargets or independent ownership endpoints; remove when relation ends']
for n,(title,rule) in enumerate(zip(state_titles,state_rules),1):
    cell(f'B02/S{n:02d}','b02-status-world.png',title,'R projection; S16=A/B world endpoints',{'triggerAndStop':rule,'all':'read logical state; no damage generated by art'},'L5 except shadow L2 / ground L0 / intro L4')
for n,title in enumerate(['AREA','LINE','PULSE RINGS','CROSS GRID'],1):
    cell(f'B03/H{n:02d}','b03-hazard-lifecycle.png',title,'G center; line G/B fixed endpoints',{
      'warning':'hazard.timer>0; actual x/y/radius or x/y/x2/y2/width',
      'resolve':'timer<=0 -> updateHazardRuntime damage once per pulse',
      'fade':'only real impactWave/particles aftermath; no extra damage',
      'repeat':'area pulseInterval resets timer; read changed radiusStep/damageStep every pulse',
      'geometry':'area remains disk even when rings decorate; line full band=2*width, target.radius additionally participates; grid is independent crossed line strips, no filled-square damage'},'L1 boundary; L4 cosmetic aftermath')
mech_titles=['WEB TERRAIN','ROOT TERRAIN','SUMMON SUCCESS','SPLIT SUCCESS','NODE BREAK','TARGET LINK','ROOT LINK','COURIER REFUND','REAL DROP','IMPACT WAVE','DEATH PARTICLES','SPECIAL ACCENTS']
mech_rules=[
 'WEB: queueMechanicTerrain, pulses/ownerMechanicUid; ends on owner death',
 'ROOT: queueMechanicTerrain poison, pulses/radiusStep/ownerMechanicUid; ends on owner death',
 'proposed flash only for actual successful unit UID; no fixed spawn count implied',
 'actual deathSpawn successful SPLINTER UIDs; consumed suppresses children; body separate',
 'generic node defeat decorative shards only; exact body fragments belong to mechanic body author',
 'living SEAL/RETICLE targetUid link; node dies before actual target freeze/area aftermath',
 'actual child.parentUid and living parent world endpoints; child itself is independent HP entity',
 'settleMechanicDefeatRuntime cargo refund immediate; no state.drops; escaped courier returns zero',
 'actual state.drops only; updateDropRuntime attraction/contact; do not double-pay Boss/courier',
 'existing impactWaves radius/life; decorative only; BEACON timer-attempt wave occurs even if no child spawned',
 'actual spawnParticle own life; consumed defeat can still have particles but no drops/deathSpawn',
 'actual style twinFinisher/dragonFinisher/astrolabeFinisher; spiderFinisher renderer-only/fallback support, not current optimized webField']
for n,(title,rule) in enumerate(zip(mech_titles,mech_rules),1):
    cell(f'B04/M{n:02d}','b04-mechanic-feedback.png',title,'G/H world center; link A/B; refund screen/HUD',{'triggerAndStop':rule},'L1 terrain / L4 feedback / L5 link / L6 refund UI')
for key,file,title in [
 ('U01','b05-start-end.png','START'),('U02','b05-start-end.png','END'),
 ('U03','b06-rewards-blueprints.png','REWARD'),('U04','b06-rewards-blueprints.png','REPAIR ALTERNATE'),('U05','b06-rewards-blueprints.png','BLUEPRINT RULE'),
 ('U06','b07-controls-placement.png','PAUSE'),('U07','b07-controls-placement.png','STATUS'),('U08','b07-controls-placement.png','DESKTOP HINT'),('U09','b07-controls-placement.png','MOBILE HINT'),('U10','b07-controls-placement.png','PLACEMENT'),('U11','b07-controls-placement.png','BUILD STATES')]:
    board='B05' if key in ['U01','U02'] else 'B06' if key in ['U03','U04','U05'] else 'B07'
    cell(board+'/'+key,file,title,'screen UI; placement G world; touch O screen press origin',{'display':'only actual component state; semantic text documented in UI mapping'},'L6 screen UI / placement L5')
cell('R01/HUD','../r01/hud-desktop-mobile.png','accepted desktop/mobile HUD','screen layout target',{'approved':'reviews/effects-ui-r01.md; no new import/runtime layout claim'},'L6')
cell('R01/HIT_BASIC','../r01/vfx-projectile-flash-hit.png','basic row impact onset/peak/fade','H world hit',{'trigger':'actual projectile hit','fade':'particle own life'},'L4')
cell('R01/HIT_CANNON','../r01/vfx-projectile-flash-hit.png','cannon row impact onset/peak/fade','H world hit',{'trigger':'actual projectile.splash','fade':'impactWave/particles own life'},'L4')
cell('R01/HIT_SNIPER','../r01/vfx-projectile-flash-hit.png','sniper row impact/trail','H hit / previous->current trail',{'trigger':'actual pierce and sniper hit','fade':'actual transient life'},'L3 trail / L4 hit')
for k in ['R01/HUD','R01/HIT_BASIC','R01/HIT_CANNON','R01/HIT_SNIPER']: cells[k]['reviewStatus']='accepted_r01_retained'

shot_cells={key:f'B01/P{n:02d}' for n,key in enumerate(['hero:PLAYER','tower:BASIC','tower:CANNON','tower:SNIPER','tower:RAPID','tower:MORTAR','tower:FROST','tower:RAIL','tower:BURST','tower:SENTINEL'],1)}
friendly_rows=[]
for item in friendly['items']:
    bodykey=item['key']; a=item['action']; kind= 'cannon' if bodykey.endswith(('CANNON','MORTAR')) else 'sniper' if bodykey.endswith(('SNIPER','RAIL')) else 'basic'
    refs=[shot_cells[bodykey], {'basic':'R01/HIT_BASIC','cannon':'R01/HIT_CANNON','sniper':'R01/HIT_SNIPER'}[kind]] if item['effects'] else []
    if a.startswith('LV'): refs.append('B02/S12')
    friendly_rows.append({'key':bodykey+':'+a,'upstreamEffects':item['effects'],'upstreamMuzzleAnchors':item['muzzleAnchors'],'effectCells':refs,
      'currentBodyReference':item['bodyReference'], 'currentRootConvention':item['rootConvention'],
      'currentDirectionReuse':item['reuse'],
      'directionRule':'friendly r03: LEFT mirror entire local rig at fixed root including P/M, then residual aim at mirrored P; RIGHT default; UP approved per-identity construction/occlusion, not arbitrary 360deg rotation; PLAYER has no launcher. External labels/level dots stay readable.',
      'eventRule':'actual projectile/shot state only; no new barrel/eye on PLAYER; BURST 4 proposed anchors, runtime count can be5',
      'anchorStatus':'upstream proposed_design_not_measured; preserve local coordinateSpace; do not use page pixels'})

enemy_effect_cells={
 'enemy.status.common':['B02/S02','B02/S05','B02/S08','B02/S11','B02/S14'],
 'enemy.contact.feedback':['R01/HIT_BASIC'], 'enemy.defeat.feedback':['B04/M11','B04/M09'],
 'enemy.shield.overlay':['B02/S01'], 'enemy.medic.aura':['B02/S15'],
 'enemy.jammer.aura':['B02/S04'], 'enemy.bomber.blast':['B04/M10'],
 'enemy.phase.opacity':['B02/S06'], 'enemy.burrow.emerge':['B02/S07','B04/M10'],
 'enemy.beacon.summon':['B04/M10','B04/M03'], 'enemy.shard.split':['B04/M11','B04/M04']}
assert set(enemy_effect_cells)==set(enemies['effectRequirements'])
enemy_rows=[]
for action in enemies['actions']:
    refs=sorted(set(c for request in action['effects'] for c in enemy_effect_cells[request]))
    enemy_rows.append({'key':action['key'],'id':action['id'],'action':action['action'],'upstreamEffects':action['effects'],'effectCells':refs,'independentSummons':action['independentSummons'],
      'currentBodySources':action.get('bodySources',[]),'currentFixedRoot':action['fixedRoot'],
      'lifecycle':'each mapped cell reads actual triggers; no body bake; BEACON M10 attempt wave is separate from M03 success flash'})

def hazard_refs(code,kind):
    # Calls are parsed as balanced parentheses; no line/area label mixing.
    refs=[]
    for match in re.finditer(r'\b'+kind+r'\s*\(',code):
        start=match.end()-1; depth=0; quote=None; esc=False; call=''
        for i in range(start,len(code)):
            ch=code[i]
            if quote:
                if esc:esc=False
                elif ch=='\\':esc=True
                elif ch==quote:quote=None
                continue
            if ch in "'\"`":quote=ch;continue
            if ch=='(':depth+=1
            elif ch==')':
                depth-=1
                if depth==0:call=code[start:i+1];break
        labels=re.findall(r"label:\s*'([^']+)'",call) or ['unlabelled']
        for label in labels:
            k='B03/H02' if kind=='queueLineHazard' else 'B03/H01'
            if kind=='queueLineHazard' and label in ['grid','crosshair','crossfire']: k='B03/H04'
            if kind=='queueAreaHazard' and label in ['frost','moon','gravity','singularity','horizon','eclipse','inferno']:k='B03/H03'
            refs.append({'cell':k,'primitive':'line' if kind=='queueLineHazard' else 'area','label':label,'lifecycleCellColumns':['WARNING','RESOLVE','FADE'],
              'geometry':'draw each real line strip, including non-perpendicular orientation; H04 is composition reference' if k=='B03/H04' else 'actual runtime disk/line footprint; no new ring-only hit area',
              'tint':'actual source identity palette; label texture optional cosmetic within same boundary',
              'sourceCall':kind+call})
    return refs

boss_rows=[]
for aid,up in bosses['abilityCatalog'].items():
    active=up['defaultEncounter'] or up['availability']=='survivor-added'
    refs=[]; geometry=[]; row=source_index.get(aid); code=row['code'] if row else ''
    # Helpers/aliases are intentionally expanded with actual optimized semantics.
    if aid in ['deadEnd']:code+='\n'+source_index['mazeCrush']['code']
    if aid in ['creepingCanopy','gardenWake']:code+='\n'+source_index['seedPods']['code']
    if aid=='webField':code+='\n'+source_index['nestBloom']['code']
    geometry=hazard_refs(code,'queueLineHazard')+hazard_refs(code,'queueAreaHazard')
    refs += [g['cell'] for g in geometry]
    if 'spawnImpactWave' in code:refs.append('B04/M10')
    if 'style:' in code:refs.append('B04/M12')
    if up['summon']:refs.append('B04/M03')
    mech_ids={m['id'] if isinstance(m,dict) else m for m in up['mechanic']}|{m['id'] if isinstance(m,dict) else m for m in up.get('relatedMechanics',[])}
    if 'WEB' in mech_ids:refs+=['B04/M01']
    if 'ROOT' in mech_ids:refs+=['B04/M02','B04/M07']
    if 'RETICLE' in mech_ids:refs+=['B04/M06','B03/H01']
    if 'SEAL' in mech_ids:refs+=['B04/M06','B02/S03']
    if 'COURIER' in mech_ids:refs+=['B04/M08']
    # All interactable mechanics may have spawn/defeat feedback, not a baked body.
    if up['mechanic']:refs+=['B04/M03','B04/M05','B02/S14']
    if 'shield' in code:refs.append('B02/S01')
    if '.hp = Math.min' in code:refs.append('B02/S15')
    if aid in ['stealMoney','repossess']:refs.append('B04/M08')
    if aid=='markTower': geometry.append({'cell':'B03/H01','primitive':'area','label':'mark','lifecycleCellColumns':['WARNING','RESOLVE','FADE'],'trigger':'only RETICLE timer fires while living; subsequent actual hazard owns warning/resolve',
      'source':'bossMechanicEntities.js:tickBossMechanicRuntime(reticle)', 'parameters':'radius32 damage22 delay0.8; actual living tower center; ownerBossUid/ownerEncounterUid',
      'geometry':'disk, not former fallback mark line; RETICLE node itself is not hazard'})
    if aid in ['freezeTower','coldSnap']: geometry.append({'cell':'B02/S03','primitive':'target state','trigger':'only SEAL living timer fires -> actual frozenTimer'})
    for mechanic_id,cell_id in [('WEB','B04/M01'),('ROOT','B04/M02')]:
        if mechanic_id in mech_ids:
            geometry.append({'cell':cell_id,'primitive':'area','label':'web' if mechanic_id=='WEB' else 'poison',
              'source':'bossOptimizedAbilities.plant -> bossMechanicEntities.queueMechanicTerrain',
              'geometry':'filled disk; mechanic body separate; no square or ring safe center',
              'parameters':'radius52 damage3 radiusStep0 slowRatio0.65' if mechanic_id=='WEB' else 'radius44 damage4 radiusStep2 slowRatio0.8',
              'lifecycleCellColumns':['WARNING','RESOLVE','FADE'],
              'trigger':'only successful living mechanic UID; delay1.1 pulses10 pulseInterval1 slowDuration1.2; actual ownership and changed radius per pulse',
              'stop':'removed when ownerMechanicUid defeated; sustained terrain removed on boss death',
              'rootChildRule':'ROOT timer may spawn child; reuses same terrain only for successful child UID, parent link reads actual parentUid' if mechanic_id=='ROOT' else None})
    boss_rows.append({'abilityId':aid,'defaultEncounter':up['defaultEncounter'],'standardOrSurvivor':active,'availability':up['availability'],'owners':up['owners'],'dispatch':up['dispatch'],
      'effectCells':sorted(set(refs)), 'geometryMappings':geometry,'windupCell':'B02/S16' if active else None,'openingCell':'B02/S09' if active else None,
      'upstreamEffect':up['effect'],'upstreamSummon':up['summon'],'upstreamMechanic':up['mechanic'],'upstreamRelatedMechanics':up.get('relatedMechanics',[]),
      'upstreamLogicalMotion':up['logicalMotion'],'runtimeEvidence':up['runtimeEvidence'],'overrideDifference':up['overrideDifference'],
      'lifecycle':'warning reads actual timer; resolve once per pulse; fade cosmetic only. State/terrain lifetimes separately follow owner and timers.',
      'motionRule':'root fixed in body canvas; read only actual world transform, no art-authored displacement','reviewStatus':'submitted_not_accepted'})
    if aid in ['stealMoney','repossess']:
        boss_rows[-1]['moneyFeedbackBinding']={'cell':'B04/M08','artRole':'positive refund example only, used after actual courier defeat&&!escaped',
          'atCast':'HUD actual money decreases; existing floating text is 击破追回 + actual cargo; never show +refund or pickup at steal time',
          'onDefeat':'actual cargo directly returned; example +12 is illustrative, amount is dynamic', 'onEscape':'no refund animation or payout'}

for row in boss_rows:
    if row['abilityId']=='tailSweep': row['effectCells']=[]; row['note']='No handler; do not invent effect.'
    if row['standardOrSurvivor']:assert row['effectCells'] or row['windupCell'],row['abilityId']
    row['lifecycleByCell']={k:cells[k]['lifecycle'] for k in row['effectCells']+[x for x in [row['windupCell'],row['openingCell']] if x]}
    row['sourceHandlerExcerpt']=source_index[row['abilityId']]['code'] if row['abilityId'] in source_index else ''
used_default=[x for x in boss_rows if x['standardOrSurvivor']]
assert len(used_default)==95
for rows in [friendly_rows,enemy_rows,boss_rows]:
    for row in rows:
        assert all(k in cells for k in row['effectCells'])

ui_rows=[
 {'component':'GameHud','cells':['R01/HUD'],'rule':'HP,money,wave/time,pause,boss members/action/phase/counterplay; retain accepted sample'},
 {'component':'BuildBar','cells':['R01/HUD','B07/U11','B07/U10'],'rule':'available towerTypes cards,cost/level/fireRate,drag,insufficient opacity,overflow; no paid context'},
 {'component':'OverlayScreen','cells':['B05/U01','B05/U02'],'rule':'START start; other nonplaying end; localhost debug button unstyled/low priority'},
 {'component':'WaveRewardOverlay','cells':['B06/U03','B06/U04','B06/U05'],'rule':'3 reward choices only; repair is alternate; unlock subsidy and blueprint upgrade from actual choice; future builds only'},
 {'component':'GameScreen paused modal','cells':['B07/U06'],'rule':'paused&&PLAYING&&!reward.active; continue/Esc'},
 {'component':'StatusBanner','cells':['B07/U07'],'rule':'only waveMsg.title/tone/accent; not invented extra subtitle'},
 {'component':'GameHud controls hint','cells':['B07/U08','B07/U09'],'rule':'dismissible; mobile30s countdown; joystick touch origin is active-only'},
 {'component':'canvas dragPlacement','cells':['B07/U10'],'rule':'canPlace/range/worldX/worldY; invalid/insufficient actual messages'},
 {'component':'TowerContextMenu','cells':[],'rule':'debug-only upgrade/downgrade; no normal-player paid upgrade'},
 {'component':'audio props','cells':[],'rule':'no currently rendered player controls; proposal-only deferred'},
 {'component':'DebugSpawnPanel/BossEditorPanel/PlaytestExport','cells':[],'rule':'keep usable; no product art packaging this revision'}]

body_reference_rows=[]
for action in bosses['actions']:
    ident=action['id']; state=action['sourceActionKey']; refs=['B02/S11','B02/S14']
    if action['group']=='mechanic':
        if ident=='WEB':refs.append('B04/M01')
        if ident=='ROOT':refs+=['B04/M02','B04/M07']
        if ident in ['SEAL','RETICLE']:refs.append('B04/M06')
        if ident=='COURIER':refs.append('B04/M08')
        if state=='TRIGGER':
            if ident=='NEST':refs.append('B04/M03')
            if ident=='SEAL':refs.append('B02/S03')
            if ident=='RETICLE':refs.append('B03/H01')
        if state in ['BREAK','FADE']:refs.append('B04/M05')
    else:
        if 'OPEN' in state or 'RECOVER' in state:refs.append('B02/S09')
        if 'WINDUP' in state:refs.append('B02/S16')
        if 'PHASE' in state or state in ['P1','P2','P3']:refs.append('B02/S15')
        if 'SOLO' in state or 'ENRAGE' in state:refs+=['B02/S10','B02/S01']
        for aid in action.get('runtimeAbilityIds',[]):
            matches=[r for r in boss_rows if r['abilityId']==aid]
            for r in matches:refs+=r['effectCells']
    body_reference_rows.append({'key':action['key'],'id':ident,'group':action['group'],'action':state,'effectCells':sorted(set(refs)),
      'currentBodySource':action.get('productionBodySource',action.get('body',{}).get('poseReference')), 'currentRoot':action['root'],
      'upstreamEffect':action['effect'],'upstreamSummon':action['summon'],'upstreamLogicalMotion':action['logicalMotion'],
      'triggerRule':'Reference pose never triggers damage/money/spawn. Only real source event/state activates an eligible mapped cell; node trigger is code timer; refund only courier defeat&&!escaped.',
      'bodyOwner':'bosses-mechanics; this row assigns external VFX only; does not produce/reapprove body',
      'runtimeAbilityIds':action.get('runtimeAbilityIds',[])})
assert len(body_reference_rows)==192

write('cell-catalog.json',{'status':'submitted_not_accepted','cells':cells})
write('production-split.json',{'owner':'effects-ui','revision':'r02','status':'submitted','sourceRevision':'accepted friendly r03 / enemies r02 / bosses-mechanics r03',
 'counts':{'friendlyActions':len(friendly_rows),'enemyActions':len(enemy_rows),'bossMechanicReferenceActions':len(body_reference_rows),'referenceAssignments':375,'bossDefaultPlusSoloSkills':95,'allBossCatalogKeys':len(boss_rows),'newBoards':7},
 'friendly':friendly_rows,'enemyEffects':{k:{'upstream':v,'cells':enemy_effect_cells[k]} for k,v in enemies['effectRequirements'].items()},'enemies':enemy_rows,'abilityCatalog':{r['abilityId']:r for r in boss_rows},'bossMechanicReferences':body_reference_rows,'ui':ui_rows,
 'anchorRule':'current friendly r03 directional rig governs P/M; numeric muzzle/root coordinates remain proposed, not measured in sheet pixels; artwork root fixed; game center unchanged',
 'currentFriendlyDirectionPolicy':friendly['directionPolicy'],
 'hardBoundaries':['3 motion kinds, 10 appearance sources','no FX body bake','COURIER refund no new pickup','BURST4 organs but runtime5shot at internallevel3','no normal paid upgrade','warning/resolve/fade never controls logical damage','BEACON attempt wave separate from success child flash'],
 'productionReadiness':'final design sources awaiting review, not alpha assets, atlas, runtime integration, animation or pixel-size proof'})
write('upstream-dependencies.json',{'readOnlyApprovedInputs':[{'owner':owner,'revision':revision,'path':str(path.relative_to(ROOT)).replace('\\','/'),'sha256':sha(path),
 'approvalEvidence':str((BASE/'reviews'/f'{owner}-{revision}.md').relative_to(ROOT)).replace('\\','/'),
 'approvalSha256':sha(BASE/'reviews'/f'{owner}-{revision}.md')} for owner,revision,path in [('friendly','r03',fpath),('enemies','r02',epath),('bosses-mechanics','r03',bpath)]],
 'additionalContracts':[{'path':str(p.relative_to(ROOT)).replace('\\','/'),'sha256':sha(p)} for p in [BASE/'friendly/submissions/r03/reuse-design.md',BASE/'bosses-mechanics/submissions/r03/effects-handoff.json']],
 'historicalInputs':'effects-ui r01 runtime evidence and approved HIT/HUD retained; upstream r01 body/effect request snapshots superseded by current accepted revisions'})

md=['# 95技能具体效果板格与生命周期','', '状态submitted；每个格的说明与生命期详见cell-catalog.json。全部新图待审，R01命中/HUD来源已通过并保留。默认技能含两幸存技能95项；旧模板五项与tailSweep单列，不冒充默认遭遇。','', '|技能|归属／调用|效果板格|生命周期／归属|','|---|---|---|---|']
for row in used_default:
    allrefs=row['effectCells']+[row['windupCell'],row['openingCell']]
    md.append('|'+row['abilityId']+'|'+row['dispatch']+' / '+','.join(str(x) for x in row['owners'])+'|'+', '.join(allrefs)+'|蓄力S16；有危区时WARNING→瞬间RESOLVE→实际波/粒子fade；无危区不新增危区。各格lifecycleByCell读取独立UID/timer；OPEN仅实际倍率>1|')
md += ['', '完整primitive、label、实际来源、召唤/机关身体所属与逻辑位移保存在production-split.json。H04交叉仅模板构图，实际若平行/倾斜则每条线按真实端点绘制。H03环仅disk的内装饰，不产生环形安全中心。S15治疗光环为复用外环的明确美术提案，无新hazard。', '', 'BEACON现有impactWave在timer尝试时产生，即使预算为0；该波用B04/M10。B04/M03独立成功闪只在实际spawn UID时使用，不能在无小怪时画孩子。', '']
(OUT/'skill-map.md').write_text('\n'.join(md),encoding='utf-8')
print(json.dumps({'friendlyActions':len(friendly_rows),'enemyActions':len(enemy_rows),'bossDefaultSkills':len(used_default),'cellCount':len(cells)},ensure_ascii=False))
